### ISSUE TITLE
Convert this to client-server application

### ISSUE THREAD

**Issue by Ladislav92** [Ladislav92/UDAS-Database#22]
There will be need for conversion of this app into web app (which will run in LAN environment).

**Comment by StevenBerdak** [comment]
I have been experimenting with Vaadin. Would this be ok to use or are you looking for pure vanilla Java?

**Comment by StevenBerdak** [comment]
Ah, so like a tomcat server/database with a rest API for accessing the server?

**Comment by Ladislav92** [comment]
Yeah, something like that was in my mind for the server side. Will see what do to with client - will it go on web and get accessed trough localhost or it will stay as JavaFX app.

**Comment by StevenBerdak** [comment]
Okay, I can start working on the server then

**Comment by Ladislav92** [comment]
There is webapp_dev branch. I have done just basic separation of stuff in project. Still has some (a lot of )work to be done.

**Comment by Ladislav92** [comment]
Need some tweaks, but split is already done.
