### ISSUE TITLE
javafx in server project

### ISSUE THREAD

**Issue by zeljic** [Ladislav92/UDAS-Database#25]
There is javafx dependency added to pom.xml file of udas-server project, also several classes depend on javafx.* package. 

Dependency should be removed and code changed to use some of other standard java libraries.

**Comment by StevenBerdak** [comment]
I believe the font-end part of the application is making use of org.openjfx. Are you suggesting removing it altogether?

As far as the back-end it looks like it has a dependency from the org.openjfx package which doesn't need to be there.

**Comment by Ladislav92** [comment]
It is because I have copied Member class from client project cointaining JavaFX SimpleStringProperty. 

Will convert it to string, until we decide will we even keep that "middle layer" or not...

**Comment by Ladislav92** [comment]
Ok, that should be removed at https://github.com/Ladislav92/UDAS-Database/commit/10c0079be006c11be139ca7f1479f66334273d0b

**Comment by zeljic** [comment]
Great.
